#!/usr/bin/env bash

prefix=/usr/local

usage="install [-prefix $prefix] [-help|-h]"

while (( $# )); do
    case $1 in
        -prefix)
            prefix=${2-}
            shift 2
            ;;
        -help|-h)
            echo "$usage"
            exit
            ;;
        *)
            echo "Unknown option $1"
            exit 1
            ;;
    esac
done

if [ -f $prefix ]; then
    echo "prefix '$prefix' is already a file, please remove it or set another installation prefix"
    exit
fi

prefix_bin=$prefix/bin
prefix_man=$prefix/man

mkdir -p $prefix_bin
mkdir -p $prefix_man/man1

cp src/* $prefix_bin/
cp man/*.1 $prefix_man/man1/
