#!/usr/bin/env -S awk -f

BEGIN {
    s = "";
}
/^\[?Thread/ {
    if (s != "") {
        print s;
        s = "";
    }
}
/#/ {
    $1 = ""
    if (s != "" ) {
        s = s "," $2
    } else {
        s = $2
    }
}
END {
    if (s != "") {
        print s
    }
}
