#!/usr/bin/env -S awk -f

BEGIN {
    s = "";
}
/^\[?Thread/ {
    if (length(s) != 0) {
        print s;
        s = "";
    }
}
/#/ {
    gsub(/\r/, "")
    $1 = ""
    if (length(s) != 0) {
        s = s ";" $0
    } else {
        s = $0
    }
}
END {
    if (length(s) != 0) {
        print s
    }
}
