#!/usr/bin/env bash

profile=profile.p4
report=report.p4

usage="p4-report [-profile profile.p4] [-report report.p4] [-help|-h]"

while (( $# )); do
    case $1 in
        -profile)
            profile=${2-}
            shift 2
            ;;
        -report)
            report=${2-}
            shift 2
            ;;
        -help|-h)
            echo "$usage"
            exit
            ;;
        *)
            echo "Unrecognized argument: $1"
            exit 1
            ;;
    esac
done

if [ ! -f "$profile" ]; then
    echo "Missing profile @ $profile, did you run p4-record?"
    exit 1
fi

cwd=$(dirname ${BASH_SOURCE[0]})
$cwd/p4-collect $profile | sort | uniq -c | sort -nr > $report
