#!/usr/bin/env bash

profile=profile.p4
report=report.p4
reverse=off
verbose=off

usage="p4-report [opts...]
 -profile        Input file to read the profile from <profile.p4>
 -report         Ouptut file to write the report into <report.p4>
 -reverse        Reverse the report order (puts hotspot at bottom).
 -verbose        Show report at standard output as well
 -help           Print this message
 -?              Print this message
"

while (( $# )); do
    case $1 in
        -profile)
            profile=${2-}
            shift 2
            ;;
        -report)
            report=${2-}
            shift 2
            ;;
        -reverse)
            reverse=on
            shift
            ;;
        -verbose)
            verbose=on
            shift
            ;;
        -help|-h|-?)
            echo "$usage"
            exit
            ;;
        *)
            echo "Unrecognized argument: $1"
            exit 1
            ;;
    esac
done

if [ ! -f "$profile" ]; then
    echo "Missing profile @ $profile, did you run p4-record?"
    exit 1
fi

sortopts=-nr
if [ $reverse = on ]; then
    sortopts=-n
fi

cwd=$(dirname ${BASH_SOURCE[0]})
if [ $verbose = on ]; then
    $cwd/p4-collect $profile | sort | uniq -c | sort $sortopts | tee $report
else
    $cwd/p4-collect $profile | sort | uniq -c | sort $sortopts > $report
fi
